"JavaScript".includes("Java");
//RETORNA VERDADEIRO SE A STRING CONTÉM A STRING PASSADA POR PARÂMETRO.
//true
"Ruby".startsWith("R");
//RETORNA VERDADEIRO SE A STRING INICIA COM A STRING PASSADA POR PARÂMETRO.
//true
"Erlang".endsWith("lang");
//RETORNA VERDADEIRO SE A STRING TERMINA COM A STRING PASSAD POR PARÂMETRO.
//true