"C++".match(/\+/g);
//RETORNA PARTES DA STRING COM BASE NA REGEXP PASSADA POR PARÂMETRO.
//'+', '+'
"Java".search(/a/);
//RETORNA A PRIMEIRA POSIÇÃO ENCONTRADA COM BASE NA REGEXP PASSADA POR PARÂMETRO.
//1
"JavaScript".replace("Java", "Ecma");
//RETORNA UMA NOVA STRING RESULTANTE DA SUBSTITUIÇÃO DA STRING OU REGEXP PASSADA NO PRIMEIRO PARÂMETRO PELO SEGUNDO PARÂMETRO.
//'EcamScript'
"JavaScript".replace(/a/g, 4);
//J4v4Script
