"JavaScript".length;
//RETORNA O TAMANHO DA STRING.
//10
"PHP".indexOf("P");
//RETORNA A PRIMEIRA POSIÇÃO ENCONTRADA DO CARACTERE PASSADO POR PARÂMETRO
//0
"PHP".lastIndexOf("P");
//RETORNA A ÚLTIMA POSIÇÃO ENCONTRADA DO CARACTER PASSADO POR PARÂMETRO
//2
"cobol".toUpperCase();
//RETORNA UMA NOVA STRING CONVERTENDO AS LETRAS PARA MAIÚCULAS.
//"COBOL"
"ALGOL".toLowerCase();
//RETORNA UMA NOVA STRING CONVERTENDO AS LETRAS PARA MINÚSCULAS.
//"algol"
