Math.abs(10);
//CONVERTE O SINAL DO NÚMERO PARA POSITIVO
//10
Math.abs(-10);
//1O
Math.ceil(1.1);
//ARREDONDA O NÚMERO PARA CIMA.
//2
Math.ceil(-1.1);
//-1 ARREDONDA PARA O PRÓXIMO INTEIRO E DIREÇÃO A ZERO.
Math.floor(9.9);
//ARREDONDA O NÚMERO PARA BAIXO.
//9
Math.floor(-9.9);
//-1O ARREDONDAMENTO SE AFASTANDO DE ZERO.
Math.round(4.5);
//ARREDONDA O NÚMERO PARA CIMA SE A PARTE DECIMAL FOR DE 5 A 9 E PARA BAIXO SE FOR DE 0 A 4.
//5
Math.round(-4.5);
//4
Math.sign(5);
//RETORNA 1 SE O NÚMERO FOR POSITIVO E -1 SE FOR NEGATIVO.
//1
Math.sign(-5);
//-1
Math.trunc(2.3);
//ELIMINA A PARTE DECIMAL DO NÚMERO TORNANDO-O INTEIRO.
//2
Math.trunc(-2.3);
//-2