Math.min(1,2,3,4,5,6);
//RETORNA O MENOR NÚMERO PASSADO POR PARÂMETRO.
//1
Math.max(1,2,3,4,5,6);
//RETORNA O MENOR NÚMERO PASSADO POR PARÂMETRO.
//2
Math.random();
//RETORNA UM NÚMERO RANDÔMICO ENTRE 0 E 1, NÃO INCLUINDO 1.
