"JavaScript".charAt(1);
//RETORNA O CARACTER NA POSIÇÃO PASSADA POR PARÂMETRO.
//"a"
"JavaScript".charCodeAt(1);
//RETORNA O CÓDIGO BASE NA POSIÇÃO PASSADA POR PARÂMETRO.
//97 CHARCODE
String.fromCharCode(97);
//RETORNA UM CARACTERE COM BASE NO CÓDIGO PASSADO POR PRÂMETRO.
//"a"
