// || = Ou       && = E 
//OPERADORES LÓGICOS SEMPRE RETORNAM SEU VALOR E NÃO SEU TIPO BOOLEANO.
0 || 2;
//2 
1 || 2;
//1  RETORANDO SOMENTE O 1 POIS ELE É VERDADEIRO, ASSIM SEM NECESSIDADE DE AVALIAR O SEGUNDO VALOR NO CASO O 2.
1 && 2;
//2 RETORNANDO SOMENTE A SEGUNDA PORTA, POIS AMBOS SÃO VERDADEIROS
0 && 2;
//2 RETORANADO A SEGUNDA PORTA, POIS SOMENTE ELE É VERDADEIRO.
