//AS ESPRESSÕES REGULSRES SÃO ESTRUTURAS FORMADAS POR UMA SEQUÊNCIA DE CARACTERES QUE ESPECIFICAM UM PADRÃO FORMAL QUE SERVEM PARA VALIDAR, EXTRAIR OU MESMO SUBSTITUIR CARACTERES DENTRO DE UMA STRING.

/john@gmail.com/;
//typeof {'object'}

//or

new RegExp("john@gmail.com")
